spring:
  application:
    name: marketData
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: company
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.tradeflow.*
        spring.json.use.type.headers: true
  jpa:
    hibernate:
      ddl-auto: none     # или ваша стратегия
    properties:
      hibernate:
        default_schema: public


  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: redis
      connect-timeout:  60000


server:
  port: 8091