
services:
  elasticsearch:
    image: elasticsearch:9.0.2
    container_name: es_local
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  kibana:
    image: kibana:9.0.2
    container_name: kibana_local
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk

  logstash:
    image: logstash:9.0.2
    container_name: logstash_local
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
    ports:
      - "5000:5000"
      - "8513:8513"
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
    depends_on:
      - elasticsearch
    networks:
      - elk
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
#    environment:
#      - STORAGE_TYPE=elasticsearch
#      - ES_HOSTS=http://elasticsearch:9200
    ports:
      - "9411:9411"
    networks:
      - elk


  prometheus:
    image: prom/prometheus
    container_name: prometheus_local
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana_local
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin        # задайте свой
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://localhost:3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - monitoring

volumes:
  es_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  elk:
    driver: bridge
  monitoring:
    driver: bridge