
services:
  elasticsearch:
    image: elasticsearch:9.0.2
    container_name: es_local
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  kibana:
    image: kibana:9.0.2
    container_name: kibana_local
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk

  logstash:
    image: logstash:9.0.2
    container_name: logstash_local
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
    ports:
      - "5000:5000"
      - "8513:8513"
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
    depends_on:
      - elasticsearch
    networks:
      - elk
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
#    environment:
#      - STORAGE_TYPE=elasticsearch
#      - ES_HOSTS=http://elasticsearch:9200
    ports:
      - "9411:9411"
    networks:
      - elk
networks:
  elk:
    driver: bridge

volumes:
  es_data:
    driver: local