spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.tradeflow.*
        spring.json.use.type.headers: true

  datasource:
    url: jdbc:postgresql://localhost:5432/order?currentSchema=your_schema_name
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none     # или ваша стратегия
    properties:
      hibernate:
        default_schema: public

server:
  port: 8080