global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Spring Boot apps with Micrometer
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8080'
          - 'host.docker.internal:8088'
          - 'host.docker.internal:8089'
          - 'host.docker.internal:8082'
          - 'host.docker.internal:8091'
          - 'host.docker.internal:8087'
          - 'host.docker.internal:8085'
          - 'host.docker.internal:8086'
          - 'host.docker.internal:8095'

